title: Ain't nothin but a thang
author: GitHub: AdamTheCreator
email: AdamTheCreator@github.com
description: > # this means to ignore newlines until "baseurl:"
  The universe is an Egg. Teaching us leasons before we hatch

# social links
twitter_username: DA_Barlow
github_username:  AdamTheCreator

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
